### ISSUE TITLE
Dependency Graph

### ISSUE THREAD

**Issue by kaitvan** [nss-evening-cohort-13/pants-group-project-coolcoders3#15]
#13 Create Dependency Graph

### Tickets WITH Dependencies
Tickets are listed in the order they need to be developed. DO NOT start a ticket before ensuring the ticket before it is completed.
- [ ] NavBar (Wendell) #18 
- [ ] HTML/JS Carousel on Homepage (Wendell) #24 
- [ ] Jean card build out for Shop page (Kaitlyn) #26 
- [ ] Button functionality for Shop page(Kaitlyn) #25 
- [ ] Build out jean fun facts (Sam) #27 
- [ ] Add functionality to fun facts button (Sam) #29
- [ ] Build out "add" button on Checkout page (Autumn) #31 
- [ ] Functionality of the checkout button for Checkout page (Autumn) #32 
- [ ] Readme (Everyone) #21 

### Tickets WITHOUT Dependencies
The tickets below DO NOT have any dependecies and can be worked in any order. They are listed by importance. Start at the top and take the next ticket.
- [ ] HTML framework for Homepage( Wendell) #19 
- [ ] HTML framework for Checkout page( Autumn) #23 
- [ ] HTML framework for Shop page( Kaitlyn) #20 
- [ ] HTML framework for About page( Sam) #22
